name: CICD

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:

  Build-Deploy:
    
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Prep Configs
      run: | 
        make _prep-env-ci
      env:
        NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
        NEXT_PUBLIC_HOSTED_ZONE_NAME: ${{ secrets.NEXT_PUBLIC_HOSTED_ZONE_NAME }}
        NEXT_PUBLIC_HOSTED_ZONE_ID: ${{ secrets.NEXT_PUBLIC_HOSTED_ZONE_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }} #Include package lock in name so on change cache is invalidated
        restore-keys: npm-

    - name: Install
      run: |
        make install

    - name: Frontend Unit Tests
      id: frontend_unit_tests
      run: make test-frontend-ci

    # - name: Backend Unit Tests
    #   id: backend_unit_tests
    #   if: success() || steps.frontend_unit_tests.outcome == 'failure' #Run backend unit tests even if frontend tests fail
    #   run: make test-backend-ci

    #Need to get tests hitting API to work
    # - name: Local e2e test
    #   run: | 
    #     make run > /dev/null 2>&1 & 
    #     make test-e2e-ci

    # - name: Infra Unit Tests
    #   run: make test-infra

    - uses: codecov/codecov-action@v2
      if: always()
      continue-on-error: true
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./backend/coverage.xml,./frontend/coverage/clover.xml
        flags: unittests # optional
        # name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)

    - name: Infra Diff
      run: make diff
      env:
        NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}
        NEXT_PUBLIC_HOSTED_ZONE_NAME: ${{ secrets.NEXT_PUBLIC_HOSTED_ZONE_NAME }}
        NEXT_PUBLIC_HOSTED_ZONE_ID: ${{ secrets.NEXT_PUBLIC_HOSTED_ZONE_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run: make deploy

    # - name: e2e test
    #   run: | 
    #     make test-e2e-deployed
    #   env:
    #     E2E_TEST_URL: awsdemo.chrishart.cloud #This is a test, for some reason the variable isn't working

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@v1.6
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  Notify:
    needs: [Build-Deploy]
    runs-on: ubuntu-latest
    if: always()

    steps:

    - name: Discord notification - UI Pass
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      if: ${{ needs.Build-Deploy.result == 'success' }}
      with:
        args: 'Success: ✅ GitHub action CI/CD pipeline passed.'

    - name: Discord notification - UI Failed
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      if: ${{(needs.Build-Deploy.result == 'failure' )}}
      with:
        args: 'Epic Fail: ❌ GitHub action CI/CD pipeline failed.'
